# Generated by Django 2.1.4 on 2019-01-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_auto_20190119_1635'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mt5positions',
            table=None,
        ),
    ]
